# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Taken from https://github.com/Mwalters75/MeowerBot/blob/master/.github/workflows/python-publish.yml

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read, write

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install build
        pip3 install --upgrade twine
    - name: Build package
      run: python3 -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@v1.5.0
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      with:
        user: Mwalters75
        password: ${{ secrets.PASSWORD }}
